removed k8s

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -1,21 +1,50 @@
-FROM maven:3.8.6-openjdk-11 AS builder
+# ---------- Build Stage ----------
+ARG JAVA_VERSION=11
+FROM maven:3.8.6-openjdk-${JAVA_VERSION} AS builder
+
+LABEL stage=builder
 
 WORKDIR /app
 
-COPY pom.xml .
+# Copy Maven configuration
+COPY pom.xml ./
 
-RUN mvn dependency:go-offline -B
+# Download dependencies (cache layer)
+RUN mvn -B dependency:resolve dependency:resolve-plugins
 
-COPY . .
+# Copy source code
+COPY src ./src
 
+# Build the application
 RUN mvn clean package -DskipTests
 
-FROM eclipse-temurin:11-jre
+# ---------- Runtime Stage ----------
+FROM eclipse-temurin:${JAVA_VERSION}-jre-jammy
+
+LABEL maintainer="Fahad Jaseem"
+LABEL version="1.0"
+LABEL description="Employee Management Backend"
 
 WORKDIR /app
 
-COPY --from=builder /app/target/*.jar app.jar
+# JVM options
+ENV JAVA_OPTS="-XX:TieredStopAtLevel=1 -XX:+UseSerialGC -Dspring.main.lazy-initialization=true -Dspring.jmx.enabled=false"
+
+# Copy application
+COPY --from=builder /app/target/employee-management-app-0.0.1-SNAPSHOT.jar app.jar
 
 EXPOSE 8080
 
-ENTRYPOINT ["java", "-jar", "app.jar"]
+HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 \
+CMD wget --spider http://localhost:8080/api/health || exit 1
+
+ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar app.jar"]
+
+
+#alternate way to write healthcheck
+# HEALTHCHECK \
+#     --interval=30s \
+#     --timeout=5s \
+#     --start-period=60s \
+#     --retries=3 \
+# CMD curl -f http://localhost:8080/api/health || exit 1
